import React from 'react'

import WorkPreview from '../components/work-preview'
import Work from '../components/work'
import ExperimentsPreview from '../components/experiments-preview'
import Experiments from '../components/experiments'
import WritingsPreview from './writings-preview'
import Writings from './writings'
import OpenSourcePreview from './open-source-preview'
import OpenSource from './open-source'
import JamsToWorkToPreview from './jams-to-work-to-preview'
import JamsToWorkTo from './jams-to-work-to'
import HomePreview from './home-preview'
import Home from './home'
import twitterLogo from '../images/twitter.png'
import dribbbleLogo from '../images/dribbble.png'
import githubLogo from '../images/github.png'
import instagramLogo from '../images/instagram.png'
import twitchLogo from '../images/twitch.png'
import spotifyLogo from '../images/spotify.png'

export default [
  {
    title: 'Twitter',
    content: twitterLogo,
    width: 46,
    height: 38,
    to: 'https://twitter.com/zacharykeith_',
    gridRow: '3',
    gridColumn: '2 / 10',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 400 + 200,
    isHomePage: false,
  },
  {
    title: 'zaaa.ch',
    content: 'zaaa.ch',
    width: null,
    height: null,
    to: '/',
    gridRow: '4',
    gridColumn: '8 / 15',
    previewComponent: <HomePreview />,
    component: <Home />,
    linkEnabled: true,
    linkVisibilityDelay: 500,
    isHomePage: true,
  },
  {
    title: 'Featured Work',
    content: 'Featured Work',
    width: null,
    height: null,
    to: '/work',
    gridRow: '9',
    gridColumn: '2 / 11',
    previewComponent: <WorkPreview />,
    component: <Work />,
    linkEnabled: true,
    linkVisibilityDelay: 600,
    isHomePage: false,
  },
  {
    title: 'Experiments',
    content: 'Experiments',
    width: null,
    height: null,
    to: '/experiments',
    gridRow: '14',
    gridColumn: '5 / 15',
    previewComponent: <ExperimentsPreview />,
    component: <Experiments />,
    linkEnabled: true,
    linkVisibilityDelay: 700,
    isHomePage: false,
  },
  {
    title: 'Dribbble',
    content: dribbbleLogo,
    width: 42,
    height: 42,
    to: 'https://dribbble.com/zacharygibson',
    gridRow: '16',
    gridColumn: '13 / 15',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 800,
    isHomePage: false,
  },
  {
    title: 'GitHub',
    content: githubLogo,
    width: 60,
    height: 50,
    to: 'https://github.com/zachgibson',
    gridRow: '18',
    gridColumn: '3 / 6',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 850,
    isHomePage: false,
  },
  {
    title: 'Instagram',
    content: instagramLogo,
    width: 44,
    height: 44,
    to: 'https://instagram.com/zacharykeith_',
    gridRow: '2',
    gridColumn: '11 / 14',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 425,
    isHomePage: false,
  },
  {
    title: 'Writings',
    content: 'Writings',
    width: null,
    height: null,
    to: '/writings',
    gridRow: '4',
    gridColumn: '4 / 10',
    previewComponent: <WritingsPreview />,
    component: <Writings />,
    linkEnabled: false,
    linkVisibilityDelay: 550,
    isHomePage: false,
  },
  {
    title: 'Twitch',
    content: twitchLogo,
    width: 106.74,
    height: 36,
    to: 'https://www.twitch.tv/zacharykeith_',
    gridRow: '7',
    gridColumn: '1 / 12',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 650,
    isHomePage: false,
  },
  {
    title: 'Open Source',
    content: 'Open Source',
    width: null,
    height: null,
    to: '/open-source',
    gridRow: '9',
    gridColumn: '8 / 16',
    previewComponent: <OpenSourcePreview />,
    component: <OpenSource />,
    linkEnabled: true,
    linkVisibilityDelay: 750,
    isHomePage: false,
  },
  {
    title: 'Jams to Work to',
    content: 'Jams to Work to',
    width: null,
    height: null,
    to: '/jams-to-work-to',
    gridRow: '14',
    gridColumn: '3 / 12',
    previewComponent: <JamsToWorkToPreview />,
    component: <JamsToWorkTo />,
    isHomePage: false,
    linkEnabled: true,
    linkVisibilityDelay: 850,
  },
  {
    title: 'Spotify',
    content: spotifyLogo,
    width: 46,
    height: 46,
    to: 'https://open.spotify.com/user/1220763445?si=HMSWJY8wQQ-SCqhlCGs8MQ',
    gridRow: '18',
    gridColumn: '9 / 12',
    previewComponent: null,
    component: null,
    linkEnabled: true,
    linkVisibilityDelay: 900,
    isHomePage: false,
  },
]
